language: python
sudo: false

notifications:
  email: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"

addons:
  apt:
    packages:
      - pandoc

install:
  - pip install pipenv
  - pipenv install --dev

script: PYTHONPATH=$PWD pipenv run pytest

after_success:
  - coveralls

before_deploy:
  - pip install pypandoc

deploy:
  provider: pypi
  user: tammoippen
  password:
    secure: yhDUquO2ro58gIoNew2C8iQYLfcrHJipjuSPwG5rbHfFAoV+PJaYXkIphgqYtYZuua9fjsraAGJZK3lKfYt06f3voI0NVkbzsEK7sNWfAKuFGlMzHEb7NJLNIYNr9hyJ9F5U9oSFUQHQC1rm4IEiNPeiQaK28bk0k9DOOU0YY0LxYDS2V4kBFJAg6atmy73maNrvYLsOPu1GGWYc10rUvVEPkR6DlmFgunGNZyW60l+6TsV8heV4QNoELv3FoL/Reg8+dbKPzN73DC19UtJwc2Q4Hi/n0xfpGrTwei4VNlr68fUWq4/qCMCZPR1iXcPf/ThIeGLfkKvgrvui5VbNnFOWKu4QWk/fbg/LapmnzFtJOVBrS9zCo/8NRUNHTo2tMExTLi1J1ZQ4efwVeOZOpbMJ9HVqoYDcz7E2hvSbWK5uD9g3JhOY+kTLHekFdSc7qpl0bkix6cRhYBtlOl1YuQxpPozD4XZs0u6B91x1PXzHHlWlDlZWHMh/ILsQ3n4nPbyuWNRiDyd/lmwWWoTlKECrX3bo0pngYKVdh/kgNbHmMVWPM4q/hpdwbV8ibWu5ZD3l2c4jruaCUjtJ9Hx7tP0UFesxNr1nJHuXuQwyTl4Z3N8gw15gMqd6rSQs6Am8aR9eT3bdVGoBdEtkppHrVYzHBw/483uz8/Y4lET42GU=
  on:
    branch: master
    tags: true
    python: "3.6"
